title:              무한의 개발
email:              gusgotoyu365@naver.com
description:        게임개발관련 블로그입니다.
author:             gusgotoyu365
url:                "https://gusgotoyu365.github.io"

# Social Profiles
twitter_username:   
github_username:    gusgotoyu365
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
